CREATE OR REPLACE STORAGE INTEGRATION s3_int
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = S3
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::660309492176:role/SnowflakeS3AccessRole'
  STORAGE_ALLOWED_LOCATIONS = ('s3://omni-recon-data/raw/');

DESC STORAGE INTEGRATION s3_int;


--Test S3 Access from Snowflake

CREATE DATABASE IF NOT EXISTS OMNI_RECON_DB;
CREATE SCHEMA IF NOT EXISTS OMNI_RECON_DB.RAW;

USE DATABASE OMNI_RECON_DB;
USE SCHEMA RAW;

CREATE OR REPLACE STAGE omni_stage
  URL = 's3://omni-recon-data/raw/'
  STORAGE_INTEGRATION = s3_int
  FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1);

LIST @omni_stage;
